### PR TITLE
added missing section & added The Future section

### PR DESCRIPTION
**Pull request by avermeulen**
@Steve can you please review and comment. There's a merge conflict :( which I will try and resolve.

### CODE REVIEW

**Comment by avermeulen** [comment]
Yeah! @SteveBarnett I managed to sort out the merge conflict.

**Comment by SteveBarnett** [comment]
@avermeulen Looks good, but `steps/the_future.html` is missing from the nav now?

**Comment by avermeulen** [comment]
@SteveBarnett I added The future link to the nav

**Comment by SteveBarnett** [comment]
👍

**Pull request merged**
