### PR TITLE
Add MVC page

### PR DESCRIPTION
**Pull request by SteveBarnett**
@avermeulen here's a first draft of an MVC page. Whatchathink?

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Comment by avermeulen** [comment]
@SteveBarnett I looked at this briefly last week. Will look at it in a bit more depth and get back to you.

**Comment by SteveBarnett** [comment]
@avermeulen Thoughts?

**Comment by avermeulen** [comment]
@SteveBarnett Please take a look I moved the file and made some minor changes. You can merge if you are happy with my changes.

**Pull request merged**
